name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Generate Package
      run: |
        dotnet clean -c Release
        dotnet build -c Release
        dotnet test -c Release --no-build --verbosity normal
        ls
        dotnet pack RequesterNet\RequesterNetLib.csproj -c Release --no-build /p:Version=${{ env.RELEASE_VERSION }}
    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push RequesterNet\bin\Release\RequesterNetLib.${{ env.RELEASE_VERSION }}.nupkg